//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArendaDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class audioDevice
    {
        public int id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public decimal price { get; set; }
        public Nullable<int> count { get; set; }
        public int status { get; set; }
        public string fio { get; set; }
        public string numberPhone { get; set; }
        public string adress { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateEnd { get; set; }
        public Nullable<int> chetOrder { get; set; }
    
        public virtual typeStatus typeStatus { get; set; }
    }
}
